services:
  ordersapi:
    container_name: ordersapi
    build: .
    ports:
      - 8080:8080
    depends_on:
      ordersapi-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ordersapi-db:3306/ordersapi"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"

  ordersapi-db:
    container_name: ordersapi-db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ordersapi
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9001:80
    depends_on:
      ordersapi-db:
        condition: service_healthy
    environment:
      PMA_HOST : ordersapi-db